# Generated by Django 6.1 on 2026-08-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, editable=False, null=True)),
                ('supplier', models.CharField(blank=True, editable=False, null=True)),
                ('qty', models.IntegerField(blank=True, editable=False, null=True)),
                ('unit', models.CharField(blank=True, editable=False, null=True)),
                ('batch_number', models.CharField(editable=False)),
                ('manufacture_date', models.DateField(editable=False)),
                ('expire_date', models.DateField(editable=False)),
            ],
            options={
                'verbose_name': '12. Batch',
                'verbose_name_plural': '12. Batch',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '02. Brand',
                'verbose_name_plural': '02. Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '01. Category',
                'verbose_name_plural': '01. Category',
            },
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '06. Godown',
                'verbose_name_plural': '06. Godown',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, null=True)),
                ('invoice_mode', models.CharField(editable=False)),
                ('taxable_value', models.IntegerField(blank=True, editable=False, null=True)),
                ('gst', models.IntegerField(blank=True, editable=False, null=True)),
                ('total', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': '08. Sales',
                'verbose_name_plural': '08. Sales',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='ABC Supplier', max_length=200, unique=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('gstin', models.CharField(blank=True, help_text='Enter 15 digit GSTIN', max_length=15, null=True, unique=True)),
                ('pan', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': '04. Supplier',
                'verbose_name_plural': '04. Supplier',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '03. Unit',
                'verbose_name_plural': '03. Unit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, editable=False, null=True)),
                ('sku', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_rate', models.DecimalField(choices=[(5.0, '5%'), (18.0, '18%')], decimal_places=2, default=18.0, max_digits=4)),
                ('stock_qty', models.PositiveIntegerField(default=0, editable=False)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
            options={
                'verbose_name': '05. Product',
                'verbose_name_plural': '05. Product',
            },
        ),
        migrations.CreateModel(
            name='Productshow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.product',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=50, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.supplier')),
            ],
            options={
                'verbose_name': '11. Payment',
                'verbose_name_plural': '11. Payment',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gst_rate', models.IntegerField(default=0, editable=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.godown')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.supplier')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productshow')),
            ],
            options={
                'verbose_name': '07. Purchase ',
                'verbose_name_plural': '07. Purchase ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('customers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_qty', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('customer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productshow')),
            ],
            options={
                'verbose_name': '09. Order ',
                'verbose_name_plural': '09. Orders',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='Cash', max_length=255)),
                ('gst_rate', models.IntegerField(default=0, editable=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_igst', models.BooleanField(default=False, verbose_name='Apply IGST')),
                ('total', models.IntegerField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.order')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productshow')),
            ],
            options={
                'verbose_name': '10. Create Invoice',
                'verbose_name_plural': '10. Create Invoice',
            },
        ),
    ]
