# Generated by Django 6.1 on 2026-10-02 09:43

import backend.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '15. Profit & Loss Report',
                'verbose_name_plural': '15. Profit & Loss Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '02. Brand',
                'verbose_name_plural': '02. Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '01. Category',
                'verbose_name_plural': '01. Category',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('name', models.CharField(choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], help_text='e.g., Rent, Salary, Electricity', max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': '14. Expense',
                'verbose_name_plural': '14. Expenses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('customers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_rate', models.IntegerField(blank=True, null=True)),
                ('customer_qty', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '08. Order ',
                'verbose_name_plural': '08. Orders',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Invoice No.')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Invoice Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '06. Purchase ',
                'verbose_name_plural': '06. Purchase ',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default=backend.models.generate_po_number, editable=False, max_length=20, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Not Sent)'), ('SENT', 'Sent to Supplier'), ('COMPLETED', 'Received/Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': '16. Purchase Order',
                'verbose_name_plural': '16. Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='ABC Supplier', max_length=200, unique=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('gstin', models.CharField(blank=True, help_text='Enter 15 digit GSTIN', max_length=15, null=True, unique=True)),
                ('pan', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('opening_balance', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Balance')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': '04. Supplier',
                'verbose_name_plural': '04. Supplier',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '03. Unit',
                'verbose_name_plural': '03. Unit',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Cash', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.order')),
            ],
            options={
                'verbose_name': '09. Bills',
                'verbose_name_plural': '09. Bills',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('composition', models.CharField(blank=True, help_text='Example: Paracetamol 500mg', max_length=255, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN / SAC')),
                ('batch', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('gst_rate', models.DecimalField(choices=[(5.0, '5%'), (18.0, '18%')], decimal_places=2, default=18.0, max_digits=4, verbose_name='GST (%)')),
                ('stock_qty', models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock')),
                ('reorder_level', models.PositiveIntegerField(default=5, help_text='Base unit me')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location/Godown')),
                ('rack', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack No.')),
                ('row', models.CharField(blank=True, max_length=50, null=True, verbose_name='Row No.')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier', verbose_name='Default Supplier for PO')),
                ('unit', models.ForeignKey(blank=True, help_text='Sabse chhoti unit (e.g. Tablet). Stock hamesha isi me store hota hai.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit', verbose_name='Base Unit')),
            ],
            options={
                'verbose_name': '05. Product',
                'verbose_name_plural': '05. Product',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_history', models.JSONField(blank=True, default=dict, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate chuni hui unit ke hisaab se', max_digits=10, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('unit_factor', models.PositiveIntegerField(default=1, editable=False)),
                ('base_qty', models.PositiveIntegerField(default=0, editable=False, verbose_name='Qty (base unit)')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount (Flat)')),
                ('gst_rate', models.IntegerField(default=0, editable=False)),
                ('gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_igst', models.BooleanField(default=False, verbose_name='Apply IGST')),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('unit', models.ForeignKey(blank=True, help_text='Khali chhodne par product ki base unit maani jayegi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='MFG Date')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='EXP Date')),
                ('qty', models.IntegerField(verbose_name='Qty')),
                ('unit_factor', models.PositiveIntegerField(default=1, editable=False)),
                ('base_qty', models.PositiveIntegerField(default=0, editable=False, verbose_name='Qty (base unit)')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Price (GST ke saath total)')),
                ('rate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Rate (per base unit)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Taxable Value')),
                ('gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gst_rate', models.IntegerField(default=0, editable=False, verbose_name='GST (%)')),
                ('rack', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack No.')),
                ('row', models.CharField(blank=True, max_length=50, null=True, verbose_name='Row No.')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('composition', models.CharField(blank=True, help_text='Example: Paracetamol 500mg', max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.purchase')),
                ('unit', models.ForeignKey(blank=True, help_text='Khali chhodne par product ki base unit maani jayegi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.PositiveIntegerField(default=10, help_text='Base unit me quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(editable=False, max_length=255, null=True)),
                ('invoice_mode', models.CharField(editable=False, max_length=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('invoice_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.invoiceitem')),
            ],
            options={
                'verbose_name': '10. Sales',
                'verbose_name_plural': '10. Sales',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='backend.supplier'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('due', models.IntegerField(blank=True, editable=False, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=50, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.supplier')),
            ],
            options={
                'verbose_name': '11. Payment',
                'verbose_name_plural': '11. Payment',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, editable=False, null=True)),
                ('supplier', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('sale_date', models.DateField(blank=True, editable=False, null=True)),
                ('customer', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('purchase_item', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.purchaseitem')),
                ('sale', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sale')),
            ],
            options={
                'verbose_name': '13. Transaction',
                'verbose_name_plural': '13. Transaction',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(help_text='1 is unit me kitni base unit hoti hain (e.g. 1 Strip = 15 Tablet to 15)', validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='backend.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit', verbose_name='Bada Unit (Strip/Box)')),
            ],
            options={
                'verbose_name': 'Unit Conversion',
                'verbose_name_plural': 'Unit Conversions',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit', verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, editable=False)),
                ('batch_number', models.CharField(editable=False, max_length=50, verbose_name='Batch')),
                ('manufacture_date', models.DateField(blank=True, editable=False, null=True, verbose_name='MFG Date')),
                ('expire_date', models.DateField(blank=True, editable=False, null=True, verbose_name='EXP Date')),
                ('rack', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('row', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('location', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='backend.product')),
                ('purchase_item', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_record', to='backend.purchaseitem')),
                ('supplier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
                ('unit', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
            options={
                'verbose_name': '07. Batch',
                'verbose_name_plural': '07. Batch',
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='unique_invoice_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product', 'unit'), name='unique_unit_per_product'),
        ),
    ]
