# Generated by Django 6.1 on 2026-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_price',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
