# Generated by Django 6.1 on 2026-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gst',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
