# Generated by Django 6.1 on 2026-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_purchase_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
