# Generated by Django 6.1 on 2026-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_payment_amount_alter_payment_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, editable=False, null=True)),
                ('supplier', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('purchase_amount', models.IntegerField(blank=True, editable=False, null=True)),
                ('sale_date', models.DateField(blank=True, editable=False, null=True)),
                ('customer', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('sale_amount', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': '13. Transaction',
                'verbose_name_plural': '13. Transaction',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
