# Generated by Django 6.1 on 2026-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_purchase_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
