# Generated by Django 6.1 on 2026-09-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_transaction_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Cash', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '10. Bills',
                'verbose_name_plural': '10. Bills',
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='name',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='batch_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.bill'),
        ),
    ]
