# Generated by Django 6.1 on 2026-09-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_bill_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='godown',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': '07. Batch', 'verbose_name_plural': '07. Batch'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': '09. Bills', 'verbose_name_plural': '09. Bills'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '08. Order ', 'verbose_name_plural': '08. Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': '06. Purchase ', 'verbose_name_plural': '06. Purchase '},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '10. Sales', 'verbose_name_plural': '10. Sales'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.DeleteModel(
            name='Godown',
        ),
    ]
