# Generated by Django 6.1 on 2026-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_invoiceitem_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
