# Generated by Django 6.1 on 2026-09-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_purchase_godown_alter_batch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_mode',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='order',
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.order'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
