# Generated by Django 6.1 on 2026-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_purchase_cgst_purchase_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='gst_rate',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
