# Generated by Django 6.1 on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_purchase_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
