# Generated by Django 6.1 on 2026-09-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_invoiceitem_invoice_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount (Flat)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.invoiceitem'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(editable=False, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expire_date',
            field=models.DateField(editable=False, verbose_name='EXP Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='manufacture_date',
            field=models.DateField(editable=False, verbose_name='MFG Date'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(5.0, '5%'), (18.0, '18%')], decimal_places=2, default=18.0, max_digits=4, verbose_name='GST (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN / SAC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXP Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='gst_rate',
            field=models.IntegerField(default=0, editable=False, verbose_name='GST (%)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='MFG Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Taxable Value'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Balance'),
        ),
    ]
