# Generated by Django 6.1 on 2026-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_invoiceitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='rack',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='row',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location/Godown'),
        ),
        migrations.AddField(
            model_name='product',
            name='rack',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack No.'),
        ),
        migrations.AddField(
            model_name='product',
            name='row',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Row No.'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rack',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack No.'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='row',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Row No.'),
        ),
    ]
