# Generated by Django 6.1 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_invoiceitem_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cgst',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sgst',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
