# Generated by Django 6.1 on 2026-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_batch_location_batch_rack_batch_row_product_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, help_text='Example: Paracetamol 500mg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='composition',
            field=models.CharField(blank=True, help_text='Example: Paracetamol 500mg', max_length=255, null=True),
        ),
    ]
