# Generated by Django 6.1 on 2026-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_invoiceitem_cgst_alter_invoiceitem_sgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_price',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
