# Generated by Django 6.1 on 2026-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_purchase_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cgst',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sgst',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
