# Generated by Django 6.1 on 2026-09-21 18:56

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_product_composition_purchase_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '15. Profit & Loss Report',
                'verbose_name_plural': '15. Profit & Loss Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('SALARY', 'Salary'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], help_text='e.g., Rent, Salary, Electricity', max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': '14. Expense',
                'verbose_name_plural': '14. Expenses',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier', verbose_name='Default Supplier for PO'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default=backend.models.generate_po_number, editable=False, max_length=20, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Not Sent)'), ('SENT', 'Sent to Supplier'), ('COMPLETED', 'Received/Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.supplier')),
            ],
            options={
                'verbose_name': '16. Purchase Order',
                'verbose_name_plural': '16. Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.PositiveIntegerField(default=10, help_text='Default order quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.purchaseorder')),
            ],
        ),
    ]
