# Generated by Django 6.1 on 2026-08-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_purchase_cgst_alter_purchase_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='InvoiceItemshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.invoiceitem')),
            ],
        ),
    ]
