# Generated by Django 6.1 on 2026-08-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_invoiceitem_cgst_alter_invoiceitem_sgst_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItemshow',
        ),
    ]
