# Generated by Django 6.1 on 2026-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_delete_invoiceitemshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_igst',
            field=models.BooleanField(default=False, verbose_name='Apply IGST'),
        ),
    ]
