# Generated by Django 6.1 on 2026-08-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_invoiceitem_igst_invoiceitem_is_igst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='purchase_order',
        ),
    ]
