# Generated by Django 6.1 on 2026-08-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_sale_product_alter_sale_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='purchase_price',
            new_name='sale_price',
        ),
    ]
