# Generated by Django 6.1 on 2026-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_purchase_price_sale_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='qty',
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
