# Generated by Django 6.1 on 2026-08-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_purchase_price_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(5.0, '5%'), (18.0, '18%')], decimal_places=2, default=18.0, max_digits=4),
        ),
    ]
