# Generated by Django 6.1 on 2026-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_product_gst_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '03. Unit',
                'verbose_name_plural': '03. Unit',
            },
        ),
        migrations.AlterModelOptions(
            name='godown',
            options={'verbose_name': '06. Godown', 'verbose_name_plural': '06. Godown'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': '10. Create Invoice', 'verbose_name_plural': '10. Create Invoice'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '09. Order ', 'verbose_name_plural': '09. Orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '11. Payment', 'verbose_name_plural': '11. Payment'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '05. Product', 'verbose_name_plural': '05. Product'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': '07. Purchase ', 'verbose_name_plural': '07. Purchase '},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '08. Sales', 'verbose_name_plural': '08. Sales'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '04. Supplier', 'verbose_name_plural': '04. Supplier'},
        ),
    ]
