# Generated by Django 6.1 on 2026-08-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_product_sale_name_remove_sale_qty_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
