# Generated by Django 6.1 on 2026-08-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_product_gst_rate'),
        ('backend', '0019_alter_sale_name'),
    ]

    operations = [
    ]
