# Generated by Django 6.1 on 2026-08-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_unit_alter_godown_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit'),
        ),
    ]
