# Generated by Django 6.1 on 2026-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_invoiceitem_unit_product_unit_purchase_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(editable=False),
        ),
    ]
