# Generated by Django 6.1 on 2026-08-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_sale_unit_alter_sale_product_alter_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit',
            field=models.CharField(blank=True, editable=False),
        ),
    ]
