# Generated by Django 6.1 on 2026-08-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_sale_product_alter_sale_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(editable=False),
        ),
    ]
