# Generated by Django 6.1 on 2026-08-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_merge_20260816_0005'),
        ('backend', '0023_alter_sale_sale_price'),
    ]

    operations = [
    ]
